### PR TITLE
[Feature] Add Page Title

### LINKED ISSUE #5: [FEATURE] Add Page titile
Currently, the title of the website is the default `React App`, change the title to `Home | SpotLight` for the Home Page and `Login | SpotLight` for the Login Page.

### PR DESCRIPTION
**Pull request by valanm22**
Fixes #5

### CODE REVIEW

**Comment by sahilsaha7773** [comment]
Hey @valanm22! I want to have different titles for the home page and login page.

**Review by sahilsaha7773 — CHANGES_REQUESTED** [review]
Different titles are required for different pages.

**Comment by sahilsaha7773** [comment]
And also please name your PRs appropriately.

**Comment by valanm22** [comment]
May I know which are those pages?

**Comment by sahilsaha7773** [comment]
> May I know which are those pages?

`Home.js` and `Login.js`

**Pull request closed without merging**
