### PR TITLE
Nowplaying

### LINKED ISSUE #10: [FEATURE] Currently Playing
Use the Spotify API to get details about the user's currently playing song and show it on the home page.

### PR DESCRIPTION
**Pull request by 03amir**
Added details of  current playing song on home page
Fixes #10

### CODE REVIEW

**Comment by sahilsaha7773** [comment]
Hi @03amir! Great work! Can you left-align this card and put it beside top artists for large screens?

**Comment by sahilsaha7773** [comment]
@03amir when no song is playing it's wasting a lot of space, can u fix that? And I noticed another bug, after logging in it shows a black screen unless I refresh the page.

**Comment by 03amir** [comment]
is that ok?

**Comment by sahilsaha7773** [comment]
seems fine, am merging it, will ask for changes if needed

**Pull request merged**
